const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
const bodyParser = require('body-parser')
const authRoutes = require('./routes/auth')
const adminRoutes = require('./routes/admin')
const deviceRoutes = require('./routes/devices')
const proposalRoutes = require('./routes/proposals')
const farmerRoutes = require('./routes/farmers')
const app = express()
app.use(cors())
app.use(bodyParser.json())
app.use('/api/auth', authRoutes)
app.use('/api/admin', adminRoutes)
app.use('/api/devices', deviceRoutes)
app.use('/api/proposals', proposalRoutes)
app.use('/api/farmers', farmerRoutes)
mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/iot_irrigation')
  .then(()=> app.listen(process.env.PORT || 4000))
  .catch(console.error)
